apiVersion: v1
kind: Secret
metadata:
  name: account-register-environment
  labels:
    app: account-register
    environment:  {{ .Values.environment }}
    tier: backend
type: Opaque
data:
  SPRING_R2DBC_PASSWORD: {{ .Values.secrets.r2dbcPassword | b64enc | quote }}
  SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG: {{ .Values.secrets.kafkaPlainLoginModule | b64enc | quote }}
