{{- range .Values.secrets.keystore }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ .app }}
    environment: {{ $.Values.environment }}
    tier: {{ .tier }}
type: Opaque
data:
  keystore.p12: {{ .keystoreFile | quote }}
  keystore-password: {{ .keystorePassword | b64enc | quote }}
---
{{- end }}
