apiVersion: v1
kind: Secret
metadata:
  name: management-environment
  labels:
    app: management
    environment:  {{ .Values.environment }}
    tier: frontend
type: Opaque
data:
  SPRING_DATA_REDIS_PASSWORD: {{ .Values.secrets.redisPassword | b64enc | quote }}
