apiVersion: v1
kind: ConfigMap
metadata:
  name: management-environment
  labels:
    app: management
    environment: {{ .Values.environment }}
    tier: frontend
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.profiles | quote }}
  SPRING_DATA_REDIS_DATABASE: {{ .Values.config.redis.database | quote }}
  SPRING_DATA_REDIS_HOST: {{ .Values.config.redis.host | quote }}
  ACCOUNT_REGISTRY_URL: {{ .Values.config.accountRegistryUrl | quote }}
  DEVICE_REGISTRY_URL: {{ .Values.config.deviceRegistryUrl | quote }}
