apiVersion: v1
kind: Service
metadata:
  name: management
  labels:
    app: management
    environment: {{ .Values.environment }}
    tier: frontend
spec:
  {{- if and .Values.loadBalancerIP (ne .Values.loadBalancerIP "") }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  {{- end }}
  selector:
    app: management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
