namespace: hlaeja-testing
environment: testing

secrets:

  # Look at /doc/k8s-docker-registry.md to make these values
  dockerRegistry:
#    - name: dockerRegistry
#      dockerRegistryConfigJson: DockerRegistryBase64==

  # Look at /doc/rsa_key.md to make these values (we use rsa so and need a public and privet key)
  jwt:
#    - name: account-jwt-private-key
#      app: account-register
#      tier: backend
#      jwtFilename: private_key.pem
#      jwtFile: AccountJwtPrivateKeyFileBase64==
#    - name: account-jwt-public-key
#      app: account-register
#      tier: frontend
#      jwtFilename: private_key.pem
#      jwtFile: AccountJwtPublicKeyFileBase64==

  # Look at /doc/keystore.md to make these values
  keystore:
#    - name: keystore-service
#      app: account-register
#      tier: backend
#      keystoreFile: ServiceKeystoreFileBase64==
#      keystorePassword: ServiceKeystorePassword

