apiVersion: v1
kind: Secret
metadata:
  name: device-configuration
  namespace: hlaeja
  labels:
    app: device-configuration
    environment: testing
    tier: backend
type: Opaque
stringData:
  SPRING_CASSANDRA_PASSWORD: "password"
