apiVersion: v1
kind: Secret
metadata:
  name: device-data-environment
  labels:
    app: device-data
    environment:  {{ .Values.environment }}
    tier: backend
type: Opaque
data:
  INFLUXDB_TOKEN: {{ .Values.secrets.influxdbToken | b64enc | quote }}
