version: '3.5'

name: hlaeja-development

volumes:
  influx-config:
  influx-data:

networks:
  develop:
    name: develop

services:
        
  influxdb:
    image: influxdb:2.7.10-alpine
    container_name: InfluxDB
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influx-data:/var/lib/influxdb2
      - influx-config:/etc/influxdb2
    networks:
      - develop
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: 
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 
      DOCKER_INFLUXDB_INIT_ORG: hlaeja_ltd
      DOCKER_INFLUXDB_INIT_BUCKET: device-data

  device-data:
    image: hlaeja-device-data:0.1.0
    container_name: DeviceData
    restart: unless-stopped
    ports:
      - "9020:8080"
    networks:
      - develop
    environment:
      SPRING_PROFILES_ACTIVE: docker
      INFLUXDB_TOKEN:
