name: hlaeja-development

networks:
  develop:
    name: develop

volumes:
  influx-config:
  influx-data:
  postgres:

services:

  device-data:
    image: hlaeja-device-data:0.1.0
    container_name: DeviceData
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
      INFLUXDB_TOKEN: influxdbToken==
    networks:
      - develop
    ports:
      - "9020:8080"

  influxdb:
    image: influxdb:2.7.10-alpine
    container_name: InfluxDB
    restart: unless-stopped
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: influx
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: influxdbToken==
      DOCKER_INFLUXDB_INIT_ORG: hlaeja_ltd
      DOCKER_INFLUXDB_INIT_BUCKET: device-data
    networks:
      - develop
    ports:
      - "8086:8086"
    volumes:
      - influx-data:/var/lib/influxdb2
      - influx-config:/etc/influxdb2

  postgres:
    image: postgres:17.1-alpine
    container_name: PostgreSQL
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD : password
    ports:
      - "5432:5432"
    networks:
      - develop
    volumes:
      - postgres:/var/lib/postgresql/data
