name: hlaeja-development

networks:
  develop:
    name: develop
    external: true

services:

  device-registry:
    image: hlaeja-device-registry:0.5.0
    container_name: DeviceRegistry
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - develop
    ports:
      - 9010:8080
    # mount a local `device_private_key.pem` into the container.
    volumes:
      - ./cert/device_private_key.pem:/app/resources/cert/private_key.pem

  device-data:
    image: hlaeja-device-data:0.1.1
    container_name: DeviceData
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
      INFLUXDB_TOKEN: influxdbToken==
    networks:
      - develop
    ports:
      - 9020:8080

  device-configuration:
    image: hlaeja-device-configuration:0.1.0
    container_name: DeviceConfiguration
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - develop
    ports:
      - 9030:8080

  device-api:
    image: hlaeja-device-api:0.4.0
    container_name: DeviceApi
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MANAGEMENT_INFLUX_METRICS_EXPORT_TOKEN: influxdbToken==
    networks:
      - develop
    ports:
      - 9000:8443
    # mount a local `device_public_key.pem` and `device_api_keystore.p12` into the container.
    volumes:
      - ./cert/device_public_key.pem:/app/resources/cert/public_key.pem
      - ./cert/device_api_keystore.p12:/app/resources/cert/keystore.p12

  registry-api:
    image: hlaeja-registry-api:0.2.0
    container_name: RegistryApi
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MANAGEMENT_INFLUX_METRICS_EXPORT_TOKEN: influxdbToken==
    networks:
      - develop
    ports:
      - 9040:8443
    # mount a local `account_public_key.pem` and `registry_api_keystore.p12` into the container.
    volumes:
      - ./cert/registry_api_keystore.p12:/app/resources/cert/keystore.p12
      - ./cert/account_public_key.pem:/app/resources/cert/public_key.pem

  account-registry:
    image: hlaeja-account-registry:0.2.0
    container_name: AccountRegistry
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - develop
    ports:
      - 9050:8080
    # mount a local `account_private_key.pem` into the container.
    volumes:
      - ./cert/account_private_key.pem:/app/resources/cert/private_key.pem

  management:
    image: hlaeja-management:0.2.0
    container_name: Management
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - develop
    ports:
      - 9060:8080
    # mount a local `account_public_key.pem` into the container.
    volumes:
      - ./cert/account_public_key.pem:/app/resources/cert/public_key.pem
