apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: hlaeja
  labels:
    environment: testing
type: kubernetes.io/dockerconfigjson
data:
  # Look at /doc/k8s-docker-registry.md to this value
  .dockerconfigjson: DockerRegistryBase64==
