apiVersion: v1
kind: Secret
metadata:
  name: registry-api-keystore
  namespace: hlaeja
  labels:
    environment: testing
type: Opaque
data:
  # Look at /doc/keystore.md, for how to make real values
  keystore.p12: RegistryApiKeystoreFileBase64==
  keystore-password: RegistryApiKeystorePasswordBase64==
