apiVersion: v1
kind: Service
metadata:
  name: device-api
  namespace: hlaeja
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app: device-api
    environment: testing
    tier: frontend
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.3.102
  selector:
    app: device-api
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
