apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb
  namespace: hlaeja
  labels:
    app: influxdb
    environment: testing
    tier: database
data:
  DOCKER_INFLUXDB_INIT_MODE: "setup"
  DOCKER_INFLUXDB_INIT_USERNAME: "influx"
  DOCKER_INFLUXDB_INIT_ORG: "hlaeja_ltd"
  DOCKER_INFLUXDB_INIT_BUCKET: "device-data"
