apiVersion: v1
kind: ConfigMap
metadata:
  name: device-api
  namespace: hlaeja
  labels:
    app: device-api
    environment: testing
    tier: frontend
data:
  SPRING_PROFILES_ACTIVE: "testing"
  SPRING_DATA_REDIS_DATABASE: "1"
  SPRING_DATA_REDIS_HOST: "redis"

  DEVICE_CONFIGURATION_URL: "http://device-configuration"
  DEVICE_DATA_URL: "http://device-data"
  DEVICE_REGISTRY_URL: "http://device-register"

  # all of this should be preset in application.yaml
  SERVER_PORT: "8443"
  SERVER_SSL_ENABLED: "true"
  SERVER_SSL_KEY_STORE: "/app/resources/cert/keystore.p12"
  SERVER_SSL_KEY_STORE_TYPE: "PKCS12"

  # This was experimental and should be removed in later versions
  MANAGEMENT_METRICS_TAGS_APPLICATION: "device-api"
  MANAGEMENT_INFLUX_METRICS_EXPORT_ENABLED: "false"
  MANAGEMENT_INFLUX_METRICS_EXPORT_URL: "http://influxdb"
  # adding this here as it's going to be deleted and is not sued internally
  MANAGEMENT_INFLUX_METRICS_EXPORT_TOKEN: "invalidInfluxDbToken=="


