apiVersion: v1
kind: Service
metadata:
  name: device-data
  namespace: hlaeja
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app: device-data
    environment: testing
    tier: backend
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.3.114
  selector:
    app: device-data
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
