apiVersion: v1
kind: Secret
metadata:
  name: device-configuration-environment
  labels:
    app: device-configuration
    environment:  {{ .Values.environment }}
    tier: backend
type: Opaque
data:
  SPRING_CASSANDRA_PASSWORD: {{ .Values.secrets.cassandraPassword | b64enc | quote }}
