apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: hlaeja
  labels:
    environment: testing
type: kubernetes.io/dockerconfigjson
data:
  # Look at /doc/k8s.md at Initialize -> Registry Secret, for how to make real values
  .dockerconfigjson: RegisterSecretBase64==
