apiVersion: v1
kind: Secret
metadata:
  name: account-jwt-private-key
  namespace: hlaeja
  labels:
    app: account-register
    environment: testing
    tier: backend
type: Opaque
data:
  # Look at /doc/rsa_key.md, for how to make real values
  private_key.pem: AccountJwtPrivateKeyFileBase64==


