apiVersion: v1
kind: Secret
metadata:
  name: account-jwt-public-key
  namespace: hlaeja
  labels:
    app: account-register
    environment: testing
    tier: frontend
type: Opaque
data:
  # Look at /doc/rsa_key.md, for how to make real values
  public_key.pem: AccountJwtPublicKeyFileBase64==
