apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: hlaeja
  labels:
    app: postgres
    environment: testing
    tier: database
type: Opaque
stringData:
  POSTGRES_PASSWORD: "password"
