apiVersion: v2
name: hlaeja-database
description: A Helm chart for the hlaeja database chart wrapper
version: 0.1.0

dependencies:

  # https://artifacthub.io/packages/helm/bitnami/postgresql
  - name: postgresql
    version: 16.7.21
    repository: "oci://registry-1.docker.io/bitnamicharts"
