apiVersion: v1
kind: Service
metadata:
  name: management
  namespace: hlaeja
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app: management
    environment: testing
    tier: frontend
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.3.101
  selector:
    app: management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
