apiVersion: v1
kind: Secret
metadata:
  name: device-data
  namespace: hlaeja
  labels:
    app: device-data
    environment: testing
    tier: backend
type: Opaque
stringData:
  INFLUXDB_TOKEN: "influxdbToken=="
