apiVersion: v1
kind: Secret
metadata:
  name: device-register-environment
  labels:
    app: device-register
    environment:  {{ .Values.environment }}
    tier: backend
type: Opaque
data:
  SPRING_R2DBC_PASSWORD: {{ .Values.secrets.r2dbcPassword | b64enc | quote }}
