apiVersion: v1
kind: Secret
metadata:
  name: account-register
  namespace: hlaeja
  labels:
    app: account-register
    environment: testing
    tier: backend
type: Opaque
stringData:
  SPRING_R2DBC_PASSWORD: "password"
