apiVersion: v1
kind: Service
metadata:
  name: account-register
  namespace: hlaeja
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app: account-register
    environment: testing
    tier: backend
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.3.111
  selector:
    app: account-register
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
