apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-api-environment
  labels:
    app: registry-api
    environment: {{ .Values.environment }}
    tier: frontend
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.profiles | quote }}
  ACCOUNT_REGISTRY_URL: {{ .Values.config.accountRegistryUrl | quote }}
  DEVICE_REGISTRY_URL: {{ .Values.config.deviceRegistryUrl | quote }}

  # all of this should be preset in application.yaml
  SERVER_PORT: "8443"
  SERVER_SSL_ENABLED: "true"
  SERVER_SSL_KEY_STORE: "/app/resources/cert/keystore.p12"
  SERVER_SSL_KEY_STORE_TYPE: "PKCS12"
