### get user by id
GET {{hostname}}/account-00000000-0000-7000-0000-000000000001

### add user
POST {{hostname}}/account
Content-Type: application/json

{
    "username": "user01010101",
    "password": "p4ssw0rd",
    "enabled": true,
    "roles": [
        "ROLE_ADMIN",
        "ROLE_TEST"
    ]
}

### update user all information
PUT {{hostname}}/account-00000000-0000-7000-0000-000000000002
Content-Type: application/json

{
    "username": "user",
    "password": "pass",
    "enabled": true,
    "roles": [
        "ROLE_TEST"
    ]
}

### update user information
PUT {{hostname}}/account-00000000-0000-7000-0000-000000000002
Content-Type: application/json

{
    "username": "user",
    "enabled": true,
    "roles": [
        "ROLE_TEST"
    ]
}
