name: development

networks:
  develop:
    name: develop
    external: true

volumes:
  cassandra:
  influx-config:
  influx-data:
  postgres:
  redis:

services:

  influxdb:
    image: influxdb:2.7.12-alpine
    container_name: InfluxDB
    restart: unless-stopped
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: influx
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: influxdbToken==
      DOCKER_INFLUXDB_INIT_ORG: hlaeja_ltd
      DOCKER_INFLUXDB_INIT_BUCKET: device-data
    networks:
      - develop
    ports:
      - 8086:8086
    volumes:
      - influx-data:/var/lib/influxdb2
      - influx-config:/etc/influxdb2

  postgres:
    image: postgres:17.5-alpine
    container_name: PostgreSQL
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD : password
    ports:
      - 5432:5432
    networks:
      - develop
    volumes:
      - postgres:/var/lib/postgresql/data

  cassandra:
    image: cassandra:5.0.4
    container_name: Cassandra
    restart: unless-stopped
    environment:
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: password
    networks:
      - develop
    ports:
      - 9042:9042
    volumes:
      - cassandra:/var/lib/cassandra

  redis:
    image: redis:8.0.3-alpine
    container_name: Redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: password
    networks:
      - develop
    ports:
      - 6379:6379
    volumes:
      - redis:/data
