apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: hlaeja
  labels:
    app: cassandra
    environment: testing
    tier: database
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.3.142
  selector:
    app: cassandra
  ports:
    - port: 9042
      targetPort: 9042
      protocol: TCP
      name: cql
