apiVersion: v1
kind: Secret
metadata:
  name: device-api-environment
  labels:
    app: device-api
    environment: {{ .Values.environment }}
    tier: frontend
type: Opaque
data:
  SPRING_DATA_REDIS_PASSWORD: {{ .Values.secrets.redisPassword | b64enc | quote }}
