apiVersion: v1
kind: ConfigMap
metadata:
  name: device-api-environment
  labels:
    app: device-api
    environment: {{ .Values.environment }}
    tier: frontend
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.profiles | quote }}
  SPRING_DATA_REDIS_DATABASE: {{ .Values.config.redis.database | quote }}
  SPRING_DATA_REDIS_HOST: {{ .Values.config.redis.host | quote }}
  DEVICE_CONFIGURATION_URL: {{ .Values.config.deviceConfigurationUrl | quote }}
  DEVICE_DATA_URL: {{ .Values.config.deviceDataUrl | quote }}
  DEVICE_REGISTRY_URL: {{ .Values.config.deviceRegistryUrl | quote }}

  # all of this should be preset in application.yaml
  SERVER_PORT: "8443"
  SERVER_SSL_ENABLED: "true"
  SERVER_SSL_KEY_STORE: "/app/resources/cert/keystore.p12"
  SERVER_SSL_KEY_STORE_TYPE: "PKCS12"
