apiVersion: v1
kind: Secret
metadata:
  name: device-register
  namespace: hlaeja
  labels:
    app: device-register
    environment: testing
    tier: backend
type: Opaque
stringData:
  SPRING_R2DBC_PASSWORD: "password"
