apiVersion: v1
kind: Service
metadata:
  name: device-register
  namespace: hlaeja
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app: device-register
    environment: testing
    tier: backend
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.3.112
  selector:
    app: device-register
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
