apiVersion: v1
kind: Secret
metadata:
  name: influxdb
  namespace: hlaeja
  labels:
    app: influxdb
    environment: testing
    tier: database
type: Opaque
stringData:
  DOCKER_INFLUXDB_INIT_PASSWORD: "password"
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "influxdbToken=="
