apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: hlaeja
  labels:
    app: influxdb
    environment: testing
    tier: database
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.3.143
  selector:
    app: influxdb
  ports:
    - port: 80
      targetPort: 8086
      protocol: TCP
      name: influxdb
