apiVersion: v1
kind: ConfigMap
metadata:
  name: device-configuration
  namespace: hlaeja
  labels:
    app: device-configuration
    environment: testing
    tier: backend
data:
  SPRING_PROFILES_ACTIVE: "testing"
  SPRING_CASSANDRA_USERNAME: "cassandra"
  SPRING_CASSANDRA_CONTACT_POINTS: "cassandra"
