environment: testing
replicas: 1
#loadBalancerIP: 10.0.3.11

docker:
  registry: dockerRegistry
  image: lulz.ltd/hlaeja/hlaeja-management:0.1.0

secrets:
  redisPassword: redisPassword
  kafkaPlainLoginModule: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"clientUsername\" password=\"clientPassword\";"

config:
  profiles: kubernetes
#  error:
#    exception: true
#    message: always
#    stacktrace: always
#  timeout: 60m
#  redis:
#    database:
#    port: 6379
#    host: dependency-redis-master
#  accountRegistryUrl: http://account-register
#  deviceRegistryUrl: http://device-register

jwtPublicKey:
  name: account-jwt-public-key
  key: public_key.pem

keystoreRef: management-keystore
